### ISSUE TITLE
Question about the purpose of this mod

### ISSUE THREAD

**Issue by TQNL** [Parker8283/BowInfinityFix#10]
Not rly an issue, but I do want to ask you something, with you being of expertise. I remember hearing in a video a long time ago that needing at least one arrow in the inventory for infinity is caused by just a few lines of conflicting code, but I can't find where I heard that from. Can you elaborate on this and give details?

**Comment by Parker8283** [comment]
I'm willing to answer your question, I just don't always have time to open my dev environment. I'll get to this eventually. Leaving open as a reminder.

**Comment by TQNL** [comment]
Sorry I never elaborated, but somehow through my foggy memory and hours of YouTube searching, I managed to find the source video. Here is everything I dug up this far: https://docs.google.com/document/d/19wTQiyeW58r5mEnjtVpD7gVbts0cTTzILczyNmvG_fg/edit?usp=sharing
I guess the only question that remains is why mojang implemented this seeming contradiction in the code. I expect anyone to know the answer, though. I just used a tutorial to view the minecraft code.

**Comment by Parker8283** [comment]
Forgot about this, but it looks like you answered your own question. Quite honestly, I'm not the "expert" here, I just wrote this mod when InfiniBows didn't get updated to 1.8, then I've been pulling it forward ever since. Seems like you probably have a better understanding of this stuff than I do :slightly_smiling_face:
