### ISSUE TITLE
Does not work for Thermal Foundation and Redstone Arsenal bows

### ISSUE THREAD

**Issue by caanthedalek** [Parker8283/BowInfinityFix#2]
As the title says, all 'reinforced' bows from Thermal Foundation and the flux-infused bow from Redstone Arsenal behave as they would without the mod. Tested with bows from EnderIO, Natura, and Botania, and only Thermal/Arsenal bows appear to be affected. Using bow infinity fix rv5 on Minecraft 1.12 in a modified version of the FTB Revelation pack via the Twitch (formerly Curse) launcher. Thanks for the mod!

**Comment by Parker8283** [comment]
That's on the mod authors to handle. The way this mod works is modifying the Minecraft `ItemBow` class to short-circuit before the check for ammo if Infinity is on the bow. Adding that fix in the same way to other mods would cause mod developers to be unhappy with me. Other mods that already work are not because of this mod, but because they added that code themselves.

So, TL;DR: Ask for it to be a feature in the CoFH Feedback center.

**Comment by caanthedalek** [comment]
Cool, thanks for the quick reply.

**Comment by Parker8283** [comment]
Over a year later, and I found a way to easily support modded bows!
If you're running rv5.1/rv6 or later, all modded bows should be supported. If they aren't, it's still on the mod author, but all they have to do is post an `ArrowNockEvent`. So if you find a modded bow that doesn't work, just tell them to do that.
